/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.intelnalFrame;

import javax.swing.JOptionPane;
import model.DAO.CapacidadeDAO;
import model.DAO.CursoDAO;
import model.DAO.DAO;
import model.Entity.Capacidade;
import model.Entity.Curso;

/**
 *
 * @author oem
 */
public class Capacidades extends javax.swing.JInternalFrame {

    /**
     * Creates new form Capacidades
     */
    public Capacidades() {
        initComponents();
        popCbox();
        popCboxCap();
    }

    private void popCbox() {
        CursoDAO dao = new CursoDAO();

        dao.findAll().forEach((c) -> {
            cboxCurso.addItem(c);
        });
    }

    private void popCboxCap() {
        CapacidadeDAO dao = new CapacidadeDAO();

        dao.findAll().forEach((d) -> {
            cboxCap.addItem(d);
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cboxCurso = new javax.swing.JComboBox<>();
        cboxCapacidade = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtACap = new javax.swing.JTextArea();
        btnSave = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cboxCap = new javax.swing.JComboBox<>();
        jSeparator1 = new javax.swing.JSeparator();
        btnLimpar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblCurso = new javax.swing.JLabel();

        cboxCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione..." }));

        cboxCapacidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Capacidade Básica", "Capacidade Técnica", "Capacidade de Gestão" }));

        txtACap.setColumns(20);
        txtACap.setRows(5);
        jScrollPane1.setViewportView(txtACap);

        btnSave.setText("Salvar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        jLabel1.setText("Editar capacidade:");

        cboxCap.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione..." }));
        cboxCap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxCapActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");

        jLabel2.setText("Selecione o curso:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                    .addComponent(cboxCapacidade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancelar))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(cboxCap, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnLimpar))
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxCap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cboxCapacidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave)
                    .addComponent(btnCancelar))
                .addGap(54, 54, 54))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        DAO<Capacidade> dao = new DAO<>();
        Capacidade cap = new Capacidade();
        cap.setTipo(cboxCapacidade.getSelectedIndex());
        Curso curso = null;
        if (cboxCurso.getSelectedIndex() != 0) {
            curso = (Curso) (cboxCurso.getSelectedItem());
            cap.setCurso(curso);
        }

        if (!txtACap.getText().isEmpty()) {
            cap.setDescricao(txtACap.getText());
        }

        try {
            if (lblCurso.getText().isEmpty()) {
                dao.save(cap);
            } else{
                Capacidade ec = (Capacidade) cboxCap.getSelectedItem();
                
                ec.setDescricao(txtACap.getText());
                ec.setTipo(cboxCapacidade.getSelectedIndex());
                if (curso != null) {
                    ec.setCurso(curso);
                } else{
                    ec.setCurso(ec.getCurso());
                }
                dao.update(ec);
            }
        } catch (Exception ex) {
            System.err.println("Erro ao salvar capacidade: " + ex);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void cboxCapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxCapActionPerformed
        Capacidade e = (Capacidade) cboxCap.getSelectedItem();
        if (e != null) {
            txtACap.setText(e.getDescricao());
            lblCurso.setText(e.getCurso().getDescricao());
        }
    }//GEN-LAST:event_cboxCapActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<Object> cboxCap;
    private javax.swing.JComboBox<String> cboxCapacidade;
    private javax.swing.JComboBox<Object> cboxCurso;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JTextArea txtACap;
    // End of variables declaration//GEN-END:variables
}
