/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.intelnalFrame;

import model.DAO.CursoDAO;
import model.DAO.DAO;
import model.DAO.ObjConhecimentoDAO;
import model.Entity.Curso;
import model.Entity.ObjConhecimento;

/**
 *
 * @author oem
 */
public class ObjConhecimentos extends javax.swing.JInternalFrame {

    /**
     * Creates new form ObjConhecimento
     */
    public ObjConhecimentos() {
        initComponents();
        popCbox(1);
        popCbox(2);
    }

    private void popCbox(Integer index) {

        switch (index) {
            case 1:
                try {
                    ObjConhecimentoDAO dao = new ObjConhecimentoDAO();
                    dao.findAll().forEach((s) -> {
                        cboxEdit.addItem(s);
                    });
                } catch (Exception e) {
                    System.out.println("Erro ao popular cbox 1: " + e);
                }
                break;
            case 2:
                try {
                    CursoDAO dao = new CursoDAO();
                    dao.findAll().forEach((s) -> {
                        cboxCurso.addItem(s);
                    });
                } catch (Exception e) {
                    System.out.println("Erro ao popular cbox 2:" + e);
                }
                break;

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtDesc = new javax.swing.JTextField();
        btnCancel = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cboxEdit = new javax.swing.JComboBox<>();
        btnLimpar = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        cboxCurso = new javax.swing.JComboBox<>();
        lblCurso = new javax.swing.JLabel();

        jLabel1.setText("Descrição");

        btnCancel.setText("Cancelar");

        btnSave.setText("Salvar");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        jLabel2.setText("Editar objeto do conhecimento");

        cboxEdit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione..." }));
        cboxEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboxEditActionPerformed(evt);
            }
        });

        btnLimpar.setText("Limpar");

        jLabel3.setText("Curso");

        cboxCurso.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione ..." }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboxEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 293, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE))
                    .addComponent(txtDesc)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 249, Short.MAX_VALUE)
                        .addComponent(btnSave)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cboxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCurso, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLimpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCurso, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel)
                    .addComponent(btnSave))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        DAO<ObjConhecimento> dao = new DAO<>();

        ObjConhecimento o = new ObjConhecimento();
        Curso curso = null;
        if (cboxCurso.getSelectedIndex() != 0) {
            curso = (Curso) cboxCurso.getSelectedItem();
            o.setCurso(curso);
        }

        if (!txtDesc.getText().isEmpty()) {
            o.setDescricao(txtDesc.getText());
        }

        try {
            if (lblCurso.getText() == null) {
                dao.save(o);
            } else {
                ObjConhecimento oc = (ObjConhecimento) cboxEdit.getSelectedItem();

                oc.setDescricao(txtDesc.getText());
                if (curso != null) {
                    oc.setCurso(curso);
                } else {
                    oc.setCurso(oc.getCurso());
                }
                dao.update(oc);
            }
        } catch (Exception ex) {
            System.err.println("Erro ao salvar capacidade: " + ex);
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void cboxEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboxEditActionPerformed
        ObjConhecimento oc = (ObjConhecimento) cboxEdit.getSelectedItem();
        if (oc != null) {
            txtDesc.setText(oc.getDescricao());
            lblCurso.setText(oc.getCurso().getNome());
        }
    }//GEN-LAST:event_cboxEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<Object> cboxCurso;
    private javax.swing.JComboBox<Object> cboxEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCurso;
    private javax.swing.JTextField txtDesc;
    // End of variables declaration//GEN-END:variables
}
