/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.home;

import controller.InternalFrameController.InternalController;
import java.beans.PropertyVetoException;
import view.intelnalFrame.Capacidades;
import view.intelnalFrame.CursoView;
import view.intelnalFrame.EleCompete;
import view.intelnalFrame.ObjConhecimentos;
import view.intelnalFrame.UniCompete;

/**
 *
 * @author luizh
 */
public class index extends javax.swing.JFrame {

    private InternalController controller = new InternalController();

    /**
     * Creates new form index
     */
    public index() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuCadastro = new javax.swing.JMenu();
        miCurso = new javax.swing.JMenuItem();
        miCapacidade = new javax.swing.JMenuItem();
        miObjConhecimento = new javax.swing.JMenuItem();
        miUnidadeComp = new javax.swing.JMenuItem();
        miElementoComp = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(800, 400));
        setPreferredSize(new java.awt.Dimension(1200, 800));
        setSize(new java.awt.Dimension(1200, 800));

        javax.swing.GroupLayout desktopPaneLayout = new javax.swing.GroupLayout(desktopPane);
        desktopPane.setLayout(desktopPaneLayout);
        desktopPaneLayout.setHorizontalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1180, Short.MAX_VALUE)
        );
        desktopPaneLayout.setVerticalGroup(
            desktopPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 757, Short.MAX_VALUE)
        );

        menuCadastro.setText("Cadastros");

        miCurso.setText("Curso");
        miCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCursoActionPerformed(evt);
            }
        });
        menuCadastro.add(miCurso);

        miCapacidade.setText("Capacidade");
        miCapacidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCapacidadeActionPerformed(evt);
            }
        });
        menuCadastro.add(miCapacidade);

        miObjConhecimento.setText("Obijetos do conhecimento");
        miObjConhecimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miObjConhecimentoActionPerformed(evt);
            }
        });
        menuCadastro.add(miObjConhecimento);

        miUnidadeComp.setText("Unidades de competências");
        miUnidadeComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miUnidadeCompActionPerformed(evt);
            }
        });
        menuCadastro.add(miUnidadeComp);

        miElementoComp.setText("Elementos de competências");
        miElementoComp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miElementoCompActionPerformed(evt);
            }
        });
        menuCadastro.add(miElementoComp);

        jMenuBar1.add(menuCadastro);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(desktopPane)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void miCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCursoActionPerformed
        CursoView cursoView = new CursoView();
        try {
            cursoView = (CursoView) controller.controllerInternal(cursoView, 1);
            desktopPane.add(cursoView);

        } catch (PropertyVetoException ex) {
            System.err.println("Erro ao abrir cadastro de curso: " + ex);
        }
    }//GEN-LAST:event_miCursoActionPerformed

    private void miCapacidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCapacidadeActionPerformed
        Capacidades capacidade = new Capacidades();
        try {
            capacidade = (Capacidades) controller.controllerInternal(capacidade, 2);
            desktopPane.add(capacidade);

        } catch (PropertyVetoException ex) {
            System.err.println("Erro ao abrir cadastro de capacidades: " + ex);
        }
    }//GEN-LAST:event_miCapacidadeActionPerformed

    private void miObjConhecimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miObjConhecimentoActionPerformed
        ObjConhecimentos objConhecimento = new ObjConhecimentos();
        try {
            objConhecimento = (ObjConhecimentos) controller.controllerInternal(objConhecimento, 3);
            desktopPane.add(objConhecimento);

        } catch (PropertyVetoException ex) {
            System.err.println("Erro ao abrir cadastro de objetos do conhecimento: " + ex);
        }
    }//GEN-LAST:event_miObjConhecimentoActionPerformed

    private void miUnidadeCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miUnidadeCompActionPerformed
        UniCompete uniCompete = new UniCompete();
        try {
            uniCompete = (UniCompete) controller.controllerInternal(uniCompete, 4);
            desktopPane.add(uniCompete);

        } catch (PropertyVetoException ex) {
            System.err.println("Erro ao abrir cadastro de unidade de competência: " + ex);
        }
    }//GEN-LAST:event_miUnidadeCompActionPerformed

    private void miElementoCompActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miElementoCompActionPerformed
        EleCompete compete = new EleCompete();
        try {
            compete = (EleCompete) controller.controllerInternal(compete, 5);
            desktopPane.add(compete);

        } catch (PropertyVetoException ex) {
            System.err.println("Erro ao abrir cadastro de elementos do conhecimento " + ex);
        }
    }//GEN-LAST:event_miElementoCompActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(index.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new index().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu menuCadastro;
    private javax.swing.JMenuItem miCapacidade;
    private javax.swing.JMenuItem miCurso;
    private javax.swing.JMenuItem miElementoComp;
    private javax.swing.JMenuItem miObjConhecimento;
    private javax.swing.JMenuItem miUnidadeComp;
    // End of variables declaration//GEN-END:variables
}
